### ISSUE TITLE
Preprocess host-species into a smaller list

### ISSUE THREAD

**Issue by j23414** [nextstrain/WNV#27]
### Context

* What are the main host species for WNV? 
* Can we summarize the current list into those main species?

### Examples

Current list seems more detailed than useful.

<img width="729" alt="Screenshot 2024-10-15 at 4 49 07 PM" src="https://github.com/user-attachments/assets/237cde24-7570-4e61-9700-1e0ee4279290">

Full list here: [host.txt](https://github.com/user-attachments/files/17386980/host.txt)

### Possible solution

After we have main host categories, we may be able to reuse the method from the rabies workflow
* https://github.com/nextstrain/rabies/commit/618bbd5601985ba7c6bda973f08a70f3a8b3266b#diff-035eb13b0d51608579a8ccff585fa32ce5a444c80cc4f76655322f50c2c01a6f

**Comment by joverlee521** [comment]
An additional use case of curating host values would be extremely useful for building out a shared command in https://github.com/nextstrain/augur/issues/1586!
