### ISSUE TITLE
Map host genus and host type

### ISSUE THREAD

**Issue by DOH-LMT2303** [nextstrain/WNV#39]
WNV NCBI records contain a column `Host` which has some information about the genus and species (i.e _Culex pipiens_). Create two categories to group and visualize the data in auspice. One category with the genus (i.e. Culex) to group all species under that genus, and another category with a host type (i.e mosquito). Similar categories have been incorporated in other WNV builds: [WNV-Foco](https://github.com/rtobiaskoch/WNV-Foco/tree/main) and [WNV-Global](https://github.com/grubaughlab/WNV-global/blob/main/auspice/WNV-Global.json)

**Comment by DOH-LMT2303** [comment]
Downloaded metadata for 23,333 WNV sequences available in NCBI as of 11-1-2024. Explored and wrangled the data in R. Added two columns Host_Genus and Host_Type to the dataset excluding where Host is blank

**Comment by DOH-LMT2303** [comment]
Created a csv mapping file that contains three columns, Host from NCBI download as of 11-1-2024, Host_Genus which is populated with the first word of the Host column, and Host_Type which classifies Host_Genus as either Mosquito, Bird, Tick, Horse, Human, or Other.
[WNVhostgenus_hosttype.csv](https://github.com/user-attachments/files/17623487/WNVhostgenus_hosttype.csv)

**Comment by j23414** [comment]
Thanks @DOH-LMT2303! Mind converting the csv to a tsv and placing the file in the `ingest/defaults` folder? Can commit to created branch `map-host-genus-and-host-type`.

After which we can draft a generalized `transform-new-columns` script that takes any mapping file and apply them to the metadata.tsv. Thanks for sharing your R code offline! We may be able to use parts of it as a starting point for the python script
