### ISSUE TITLE
Add Nextclade extension

### ISSUE THREAD

**Issue by j23414** [nextstrain/WNV#43]
### Context

Add the Nextclade extension to `auspice_config.json` to enable "View in other platforms"

<img width="1052" alt="Screenshot 2024-11-18 at 2 10 30 PM" src="https://github.com/user-attachments/assets/243fefe1-76c8-4dc2-b6f4-ee7f2aa9aaa3">

### Possible solution

* Probably requires a similar fix to https://github.com/nextstrain/seasonal-flu/pull/197

**Comment by jameshadfield** [comment]
> Add the Nextclade extension to auspice_config.json to enable "View in other platforms"

It doesn't need any extension it just needs a root-sequence (either in-line or via sidecar JSON)

**Comment by j23414** [comment]
Thanks @jameshadfield! Agree that `--include-root-sequence-inline` flag needed to be added to the `augur export` statement (or uploading a sidecar) and directly addresses the "dataset doesn't have a root sequence" message. It is useful to point this out.

To get reasonably functioning Nextclade link-out that assigns lineages based on a live tree, I'm still fiddling with the nextclade extension in the auspice.json file on the [add-nextclade-extension branch](https://github.com/nextstrain/WNV/compare/main...add-nextclade-extension). Right now, it only works with 1A lineage calls so I'm looking into the alignment parameters. 

* Nextclade Link Out: https://clades.nextstrain.org/?dataset-json-url=https%3A%2F%2Fnext.nextstrain.org%2Fstaging%2FWNV%2Fhost
* Using these example sequences: https://github.com/nextstrain/WNV/blob/main/phylogenetic/example_data/sequences.fasta

<img width="1130" alt="Screenshot 2024-11-19 at 4 19 34 AM" src="https://github.com/user-attachments/assets/68f997e3-fd89-4f89-a0d7-3adf72a8ada4">

I'm also wondering if it's because the USA-based lineages (pre-NY, NY99, SW02, WN03) are all 1A and are annotated as `clade_membership` (with the rest as empty string or `?` values) and that's why other lineages (1B, 2, 3, 4, 5, 7, 8.) are not showing up. Any insights welcome!

I basically downloaded your [clade-llb-inline-extended](https://next.nextstrain.org/staging/james/mpox/clade-IIb-inline-extended) auspice file to try to figure out how to use nextclade extensions in auspice JSON, but I'm probably missing something.

**Comment by joverlee521** [comment]
The lineages/clades are not going to get properly assigned for all samples because the internal nodes do not have clade labels.

**Comment by jameshadfield** [comment]
> I basically downloaded your [clade-llb-inline-extended](https://next.nextstrain.org/staging/james/mpox/clade-IIb-inline-extended) auspice file to try to figure out how to use nextclade extensions in auspice JSON, but I'm probably missing something.

P.S. That was just me trying out some things to debug a mpox issue ([internal slack thread](https://bedfordlab.slack.com/archives/C0K3GS3J8/p1729729077111499)). [Here](https://docs.nextstrain.org/projects/nextclade/en/latest/user/input-files/04-reference-tree.html#extensions) are the nextclade docs. I think you can embed any option in `pathogen.json` within that block. We also use an extensions block [in the h5n1-cattle-outbreak build](https://github.com/nextstrain/avian-flu/blob/da8a4f9b8841ce7b219811f070d2ab73776f65ba/config/h5n1-cattle-outbreak/auspice_config_h5n1-cattle-outbreak.json#L21-L45) as well as the recently added seasonal-flu builds.

I would think WNV should work pretty well for clade assignment without needing to add set an `extensions` block, although you can of course enhance it by using one.

**Comment by j23414** [comment]
Got it thanks! I'll submit a PR with the working changes:

<img width="1510" alt="Screenshot 2024-11-20 at 2 09 49 PM" src="https://github.com/user-attachments/assets/dbda3f5a-c765-4203-b79b-f40da4a79978">
